var _page_settings = {
	"your_office" : "your office"
	,"offices" : {
		"contacts_office" : {
			"kyiv" : "Headquarters"
			,"lviv" : "Western Ukrainian Bureau"
			,"uzhgorod" : "Transcarpatian Bureau"
			,"lutsk" : "Representative Office in Volyn and Rivne Regions"
			,"frankovsk" : "Representative Office in Ivano-Frankivsk Region"
			,"donetsk" : "Eastern Ukrainian Representative Office"
			,"ternopil" : "Representative Office in Ternopil Region"
			,"chernivtsi" : "Representative Office in Chernivtsi Region"
			,"vinnytsia" : "Agency in Vinnytsya Region"
			,"zhytomyr" : "Agency in Zhytomyr Region"
			,"zaporizhia" : "Agency in Zaporizhia Region"
			,"kropyvnytskyi" : "Agency in Kirovohrad Region"
			,"sumy" : "Agency in Sumy Region"
			,"kharkiv" : "Agency in Kharkiv Region"
			,"kherson" : "Agency in Kherson Region"
			,"khmelnytskyy" : "Agency in Khmelnytskyy Region"
			,"cherkasy" : "Agency in Cherkasy Region"
			,"dnipro" : "Agency in Dnipro Region"
		}
		,"contacts_adress" : {
			"kyiv" : "2-2А Zolotovoritska St., Kyiv 01030"
			,"lviv" : "31 Rynok Sqr., Lviv 79008"
			,"uzhgorod" : "39 Sobranetska St., Uzhgorod 88000"
			,"lutsk" : "6/4 Kyiv Square, Lutsk 43010"
			,"frankovsk" : "5/1А Zaliznychna St., Ivano-Frankivsk 76000"
			,"donetsk" : "12 Panfilova Ave., Donetsk 83087"
			,"ternopil" : "23 Ruska St., Ternopil 46001"
			,"chernivtsi" : "61 Holovna St., Chernivtsi 58000"
			,"vinnytsia" : "38/2 Soborna St., Vinnytsia 21050"
			,"zhytomyr" : "17 Haharina St., Office 1A, Zhytomyr 10002"
			,"zaporizhia" : "22 Metalurhiv St., Zaporizhia 69006"
			,"kropyvnytskyi" : "51A/3 Pashutina St., Kirovohrad 25006"
			,"sumy" : "25/16 Soborna St., Sumy 40000"
			,"kharkiv" : "108 Traktorobudivnykiv St., Office 39, Kharkiv 61118"
			,"kherson" : "20 Perekopska St., Kherson 73000"
			,"khmelnytskyy" : "46 Proskurivska St., Khmelnytskyy 29001"
			,"cherkasy" : "258 Shechenka Blvd., Cherkasy 18000"
			,"dnipro" : "2 Panikakhy St., Dnipro, 49600"
		}
		,"contacts_phone1" : {
			"kyiv" : "+38 (044) 288-03-90"
			,"lviv" : "+38 (032) 235-55-42"
			,"uzhgorod" : "+38 (0312) 23-73-27"
			,"lutsk" : ""
			,"frankovsk" : "+38 (0342) 75-14-90"
			,"donetsk" : "+38 (062) 253-37-41"
			,"ternopil" : ""
			,"chernivtsi" : ""
			,"vinnytsia" : ""
			,"zhytomyr" : ""
			,"zaporizhia" : ""
			,"kropyvnytskyi" : ""
			,"sumy" : "+38 (097) 917-13-75"
			,"kharkiv" : ""
			,"kherson" : ""
			,"khmelnytskyy" : ""
			,"cherkasy" : ""
			,"dnipro" : "+380 97 207-72-24"
		}
		,"contacts_phone2" : {
			"kyiv" : "+38 (044) 234-52-08"
			,"lviv" : "+38 (032) 235-66-22"
			,"uzhgorod" : ""
			,"lutsk" : ""
			,"frankovsk" : ""
			,"donetsk" : ""
			,"ternopil" : ""
			,"chernivtsi" : ""
			,"vinnytsia" : ""
			,"zhytomyr" : ""
			,"zaporizhia" : ""
			,"kropyvnytskyi" : ""
			,"sumy" : ""
			,"kharkiv" : ""
			,"kherson" : ""
			,"khmelnytskyy" : ""
			,"cherkasy" : ""
			,"dnipro" : ""
		}
		,"contacts_fax" : {
			"kyiv" : "+38 (044) 279-28-35"
			,"lviv" : "+38 (032) 235-46-04"
			,"uzhgorod" : "+38 (0312) 64-32-05"
			,"lutsk" : ""
			,"frankovsk" : ""
			,"donetsk" : "+38 (062) 385-45-99"
			,"ternopil" : ""
			,"chernivtsi" : ""
			,"vinnytsia" : ""
			,"zhytomyr" : ""
			,"zaporizhia" : ""
			,"kropyvnytskyi" : ""
			,"sumy" : ""
			,"kharkiv" : ""
			,"kherson" : ""
			,"khmelnytskyy" : ""
			,"cherkasy" : ""
			,"dnipro" : ""
		}
		,"contacts_phoneFax" : {
			"kyiv" : ""
			,"lviv" : ""
			,"uzhgorod" : ""
			,"lutsk" : "+38 (0332) 72-96-26"
			,"frankovsk" : ""
			,"donetsk" : ""
			,"ternopil" : "+38 (0352) 52-75-75"
			,"chernivtsi" : "+38 (0372) 51-28-00"
			,"vinnytsia" : "+38 (0432) 35-42-86"
			,"zhytomyr" : "+38 (0412) 34-35-44"
			,"zaporizhia" : "+38 (061) 212-04-47"
			,"kropyvnytskyi" : "+38 (0522) 24-77-06"
			,"sumy" : ""
			,"kharkiv" : "+38 (057) 710-33-31"
			,"kherson" : "+38 (0552) 26-22-26"
			,"khmelnytskyy" : "+38 (0382) 70-48-49"
			,"cherkasy" : "+38 (0472) 32-00-90"
			,"dnipro" : ""
		}
		,"contacts_email" : {
			"kyiv" : "info@ukrinur.com"
			,"lviv" : "info@ukrinur.com"
			,"uzhgorod" : "info@ukrinur.com"
			,"lutsk" : "info@ukrinur.com"
			,"frankovsk" : "info@ukrinur.com"
			,"donetsk" : "info@ukrinur.com"
			,"ternopil" : "info@ukrinur.com"
			,"chernivtsi" : "info@ukrinur.com"
			,"vinnytsia" : "info@ukrinur.com"
			,"zhytomyr" : "info@ukrinur.com"
			,"zaporizhia" : "info@ukrinur.com"
			,"kropyvnytskyi" : "info@ukrinur.com"
			,"sumy" : "info@ukrinur.com"
			,"kharkiv" : "info@ukrinur.com"
			,"kherson" : "info@ukrinur.com"
			,"khmelnytskyy" : "info@ukrinur.com"
			,"cherkasy" : "info@ukrinur.com"
			,"dnipro" : "info@ukrinur.com"
		}
    }
};

settings.init(_page_settings);