var _page_settings = {
	"your_office" : "your office"
	,"offices" : {
		"contacts_office" : {
			"kyiv" : "Центральне бюро"
			,"lviv" : "Західноукраїнське бюро"
			,"uzhgorod" : "Закарпатське бюро"
			,"lutsk" : "Представництво у Волинській та Рівненській областях"
			,"frankovsk" : "Представництво в Івано-Франківській області"
			,"donetsk" : "Східноукраїнське представництво"
			,"ternopil" : "Представництво в Тернопільській області"
			,"chernivtsi" : "Представництво у Чернівецькій області"
			,"vinnytsia" : "Приймальня у Вінницькій області"
			,"zhytomyr" : "Приймальня у Житомирській області"
			,"zaporizhia" : "Приймальня в Запорізькій області"
			,"kropyvnytskyi" : "Приймальня в Кіровоградській області"
			,"sumy" : "Приймальня у Сумській області"
			,"kharkiv" : "Приймальня у Харківській області"
			,"kherson" : "Приймальня у Херсонській області"
			,"khmelnytskyy" : "Приймальня в Хмельницькій області"
			,"cherkasy" : "Приймальня у Черкаській області"
			,"dnipro" : "Представництво в Дніпропетровській області"
		}
		,"contacts_adress" : {
			"kyiv" : "вул. Золотоворітська, 2-2А, м. Київ, 01030"
			,"lviv" : "пл. Ринок, 31, м. Львів, 79008"
			,"uzhgorod" : "вул. Собранецька, м. Ужгород, 3988000"
			,"lutsk" : "Київський майдан, 6, к. 4 (4-й поверх), м. Луцьк, 43010"
			,"frankovsk" : "вул. Залізнична, 5/1А, м. Івано-Франківськ, 76000"
			,"donetsk" : "пр. Панфілова, 112, м. Донецьк, 83087"
			,"ternopil" : "вул. Руська, 23, м. Тернопіль, 46001"
			,"chernivtsi" : "вул. Головна, 61, м. Чернівці, 58000"
			,"vinnytsia" : "вул. Соборна, 38, офіс 2, м. Вінниця, 21050"
			,"zhytomyr" : "вул. Гагаріна, 17, оф. 1А, м. Житомир, 10002"
			,"zaporizhia" : "просп. Металургів, 22, кв. 25, м. Запоріжжя, 69006"
			,"kropyvnytskyi" : "вул. Пашутінська, 51А, кв. 3, м. Кропівницький, 25006"
			,"sumy" : "вул. Соборна, 25, к. 16, м. Суми, 40000"
			,"kharkiv" : "пр. Тракторобудівників, 108, к. 39, м. Харків, 61118"
			,"kherson" : "вул. Перекопська, 20, м. Херсон, 73024"
			,"khmelnytskyy" : "вул. Проскурівська, 46, м. Хмельницький, 29001"
			,"cherkasy" : "бул. Шевченка, 258, м. Черкаси, 18000"
			,"dnipro" : "вул. Панікахи, 2, м. Дніпро, 49600"
		}
		,"contacts_phone1" : {
			"kyiv" : "+38 (044) 288-03-90"
			,"lviv" : "+38 (032) 235-55-42"
			,"uzhgorod" : "+38 (0312) 23-73-27"
			,"lutsk" : ""
			,"frankovsk" : "+38 (0342) 75-14-90"
			,"donetsk" : "+38 (062) 253-37-41"
			,"ternopil" : ""
			,"chernivtsi" : ""
			,"vinnytsia" : ""
			,"zhytomyr" : ""
			,"zaporizhia" : ""
			,"kropyvnytskyi" : ""
			,"sumy" : "+38 (097) 917-13-75"
			,"kharkiv" : ""
			,"kherson" : ""
			,"khmelnytskyy" : ""
			,"cherkasy" : ""
			,"dnipro" : "+380 97 207-72-24"
		}
		,"contacts_phone2" : {
			"kyiv" : "+38 (044) 234-52-08"
			,"lviv" : "+38 (032) 235-66-22"
			,"uzhgorod" : ""
			,"lutsk" : ""
			,"frankovsk" : ""
			,"donetsk" : ""
			,"ternopil" : ""
			,"chernivtsi" : ""
			,"vinnytsia" : ""
			,"zhytomyr" : ""
			,"zaporizhia" : ""
			,"kropyvnytskyi" : ""
			,"sumy" : ""
			,"kharkiv" : ""
			,"kherson" : ""
			,"khmelnytskyy" : ""
			,"cherkasy" : ""
			,"dnipro" : ""
		}
		,"contacts_fax" : {
			"kyiv" : "+38 (044) 279-28-35"
			,"lviv" : "+38 (032) 235-46-04"
			,"uzhgorod" : "+38 (0312) 64-32-05"
			,"lutsk" : ""
			,"frankovsk" : ""
			,"donetsk" : "+38 (062) 385-45-99"
			,"ternopil" : ""
			,"chernivtsi" : ""
			,"vinnytsia" : ""
			,"zhytomyr" : ""
			,"zaporizhia" : ""
			,"kropyvnytskyi" : ""
			,"sumy" : ""
			,"kharkiv" : ""
			,"kherson" : ""
			,"khmelnytskyy" : ""
			,"cherkasy" : ""
			,"dnipro" : ""
		}
		,"contacts_phoneFax" : {
			"kyiv" : ""
			,"lviv" : ""
			,"uzhgorod" : ""
			,"lutsk" : "+38 (0332) 72-96-26"
			,"frankovsk" : ""
			,"donetsk" : ""
			,"ternopil" : "+38 (0352) 52-75-75"
			,"chernivtsi" : "+38 (0372) 51-28-00"
			,"vinnytsia" : "+38 (0432) 35-42-86"
			,"zhytomyr" : "+38 (0412) 34-35-44"
			,"zaporizhia" : "+38 (061) 212-04-47"
			,"kropyvnytskyi" : "+38 (0522) 24-77-06"
			,"sumy" : ""
			,"kharkiv" : "+38 (057) 710-33-31"
			,"kherson" : "+38 (0552) 26-22-26"
			,"khmelnytskyy" : "+38 (0382) 70-48-49"
			,"cherkasy" : "+38 (0472) 32-00-90"
			,"dnipro" : ""
		}
		,"contacts_email" : {
			"kyiv" : "info@ukrinur.com"
			,"lviv" : "info@ukrinur.com"
			,"uzhgorod" : "info@ukrinur.com"
			,"lutsk" : "info@ukrinur.com"
			,"frankovsk" : "info@ukrinur.com"
			,"donetsk" : "info@ukrinur.com"
			,"ternopil" : "info@ukrinur.com"
			,"chernivtsi" : "info@ukrinur.com"
			,"vinnytsia" : "info@ukrinur.com"
			,"zhytomyr" : "info@ukrinur.com"
			,"zaporizhia" : "info@ukrinur.com"
			,"kropyvnytskyi" : "info@ukrinur.com"
			,"sumy" : "info@ukrinur.com"
			,"kharkiv" : "info@ukrinur.com"
			,"kherson" : "info@ukrinur.com"
			,"khmelnytskyy" : "info@ukrinur.com"
			,"cherkasy" : "info@ukrinur.com"
			,"dnipro" : "info@ukrinur.com"
		}
    }
};

settings.init(_page_settings);